# Generated by Django 4.0.2 on 2022-07-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsaras', '0004_alter_product_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
