# Generated by Django 4.0.2 on 2022-07-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apsaras', '0006_rename_price_order_unit_price_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='apsaras.product'),
        ),
    ]
